#!/bin/bash
# ---------------------------------------------------------------------------
# This script installs files and services specific to the project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/cp-sysmon
# ---------------------------------------------------------------------------

PROJECT="cp_sysmon"

# --- install specific files   ----------------------------------------------

install_files() {
  echo -e "[INFO] installing project files" 2>&1

  rand="$RANDOM"
  if [ -f /etc/${PROJECT}.json ]; then
    # save current configuration
    mv /etc/${PROJECT}.json /etc/${PROJECT}.json.$rand
  fi

  for f in `find $(dirname "$0")/../files/ -type f -not -name "*.pyc"`; do
    target="${f#*files}"
    target_dir="${target%/*}"
    [ ! -d "$target_dir" ] && mkdir -p "$target_dir"
    cp "$f" "$target"
    chown root:root "$target"
  done

  chmod 755 "/usr/local/bin/$PROJECT.py"
  chmod 644 "/etc/$PROJECT.json"
  chmod 644 "/etc/udev/rules.d/99-$PROJECT.rules"
  chmod 644 "/etc/systemd/system/$PROJECT@.service"

  # restore old configuration
  if [ -f /etc/${PROJECT}.json.$rand ]; then
    mv -f /etc/${PROJECT}.json /etc/${PROJECT}.json.new
    mv /etc/${PROJECT}.json.$rand /etc/${PROJECT}.json
    echo -e "\nnew version of configuration file: /etc/${PROJECT}.json.new"
  fi
}

# --- main program   --------------------------------------------------------

install_files

echo "[INFO] installation completed"
